#!/bin/bash
set -e

function run {
    java -jar blogix.jar run
}
function compile {
    java -jar blogix.jar compile 
}
function fnexport {
    java -jar blogix.jar export
    if [[ -d public ]]; then
        cp -r public export/public
    fi
}
function help {
    echo "Usage: blogix [ run | compile | export | help]"
}


case $1 in
    run)
        shift
        run $@
        exit 0
        ;;
    compile)
        shift
        compile $@
        exit 0
        ;;
    export)
        shift
        fnexport $@
        exit 0
        ;;
    help)
        shift
        help $@
        exit 0
        ;;
    *)
        shift
        echo "Unknown command: '$1'"
        help
        exit 0
        ;;
esac
help
